version: '3'
# linehopper composed containers
services:
  api:
    container_name: api
    build: 
      context: './api'
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - ACCESS_TOKEN_SECRET=THEHAPPYDOGWALKSFAST@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@d
      - REFRESH_TOKEN_SECRET=THESADCATWALKSSLOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!q
      - user=postgres
      - pass=admin123
      - port=5432
      - host=db
      - pgdb=postgres
      - url=linehopperku.com
      - MJ_APIKEY_PUBLIC = 6c9ea700e37a55dbbeb6346560d06b49
      - MJ_APIKEY_PRIVATE = 9964dd6e37b655df814b213403bf5dd8
    depends_on:
      - db

  db:
    container_name: db
    image: 'ramazanpolat/postgres_cron:11'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=linehoptest
    volumes:
      - pgdata:/var/lib/postgresql/data # fully q path over rel path

  client:
    container_name: client
    build: 
      context: './client'
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment: 
      - url=127.0.0.1
      - CHOKIDAR_USEPOLLING=true # <---- this enables the hot reloading
volumes:
  pgdata: {}

