PUT http://localhost:3000/api/useraccount/forgotPassword
Content-Type: application/json

{
"newPassword": "newpasswordtest",
"email": "test@test.com"

}
###


POST http://localhost:3000/api/useraccount
Content-Type: application/json 




{
  "email":"user@user.com",
  "password":"user",
  "role": "user"
}

###
GET http://localhost:3000/api/check/jsmit665@live.kutztown.edu
Content-Type: application/json

### Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "user@user.com",
  "password": "user"
}
### Refresh
GET http://localhost:3000/api/refresh
Content-Type: application/json

###
GET http://localhost:3000/api/locationhistory/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIxZjkwMzYwMi0xZTY1LTQ5NWEtOTQ0MC00MTlhYmIxN2M1MWUiLCJlbWFpbCI6Impha2VzcGFtYWNjMjg0QGdtYWlsLmNvbSIsImlhdCI6MTY4MDMwNjgyOCwiZXhwIjoxNjgwMzA3NzI4fQ.yNClkgu_nAZiL8TPesxbLzVkuAT-mP5HOHLC0-mLU2M

###
GET http://localhost:3000/api/userrole 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI3YmFlZGM0Yy0zNTQ5LTRkOGItYWJhOS1jNWZhYzEzMGI1MzIiLCJlbWFpbCI6InVzZXJAdXNlci5jb20iLCJpYXQiOjE2Nzg4MzMyOTEsImV4cCI6MTY3ODgzNDE5MX0.OkV5T-aEA-UtZ0z0Ipe78bP5YIZLJj9sWFxzvNZV1CU

{
  "userid": "7baedc4c-3549-4d8b-aba9-c5fac130b532"
}
###

POST http://localhost:3000/api/location
Content-Type: application/json 
{
  "rid":1111,
  "rname":"user"
}

###
